#!/bin/bash
rm -rf /tmp/hsp.log
chmod 777 /tmp/hsp.log

address=$(cat /home/ethos/address)
echo $address
worker=$(cat /home/ethos/worker)
echo $worker
sudo killall aionminer
HSPMiner -bpool btm.f2pool.com:9221 -bwal bm1ql7p8l2q2chxzvdw76u9v6n98tur09xjshhmns6 -bworker $worker -bpsw passd -logfile -api 127.0.0.1:16666 >/tmp/hsp.log 2>&1 &
